### ISSUE TITLE
Commands that require arguments aren't working

### ISSUE THREAD

**Issue by dadaday** [maddevsio/comedian#175]
Commands like /adminadd and /adminremove are giving the same error: index out of range

For instance in this screenshot, /adminlist works as expected, but /adminadd doesn't
<img width="590" alt="screen shot 2018-09-15 at 1 43 47 am" src="https://user-images.githubusercontent.com/7059618/45571790-355b3400-b889-11e8-9be2-6e142b572dde.png">

I guess the reason is this piece of code: 
```
slackUserID := strings.Replace(result[0], "<@", "", -1)
userName := strings.Replace(result[1], ">", "", -1)
```

<img width="966" alt="screen shot 2018-09-15 at 1 47 07 am" src="https://user-images.githubusercontent.com/7059618/45571818-47d56d80-b889-11e8-8b03-f769373779ac.png">

**Comment by anatoliyfedorenko** [comment]
@dadaday when adding slash commands, did you select "Escape channels, users, and links sent to your app" option in api.slack.com? if you this will resolve your issue 90%. I will add this instruction to documentation as well

**Comment by dadaday** [comment]
@anatoliyfedorenko thanks, that did the trick!

I am not getting that error anymore, however I stumbled upon another error message.
This time it's 402 message:
`level=error msg="slack: GetGroupInfo failed: channel_not_found"`
I do think that this time it's because I missed some steps while configuring it for my workspace. 

My current status:

- I am a workspace admin
- I am adding the bot to the private group
- I've set COMEDIAN_MANAGER_SLACK_CHAN_GENERAL to the id of the #general channel
- Don't know what to do with COMEDIAN_COLLECTOR vars

It'd be great if you added more detailed explanation of the setup process, and of the env variables, particularly COMEDIAN_COLLECTOR_TOKEN and COMEDIAN_COLLECTOR_URL.

**Comment by dadaday** [comment]
> @anatoliyfedorenko thanks, that did the trick!
> 
> I am not getting that error anymore, however I stumbled upon another error message.
> This time its status code is 400:
> 
> <img alt="screen shot 2018-09-16 at 1 10 07 am" width="813" src="https://user-images.githubusercontent.com/7059618/45589756-51280e00-b94d-11e8-91cb-ed563d5cad72.png">
> 
> From the log: `level=error msg="slack: GetGroupInfo failed: channel_not_found"`
> 
> I do think that this time it's because I missed some steps while configuring it for my workspace.
> 
> My current status:
> 
> * I am a workspace admin
> * I am adding the bot to the private channel
> * I've set COMEDIAN_MANAGER_SLACK_CHAN_GENERAL to the id of the #general channel
> * Don't know what to do with COMEDIAN_COLLECTOR vars
> 
> It'd be great if you added more detailed explanation of the setup process, and of the env variables, particularly COMEDIAN_COLLECTOR_TOKEN and COMEDIAN_COLLECTOR_URL.

I tried adding the bot to the public channel, and it worked.

**Comment by anatoliyfedorenko** [comment]
@dadaday will do. Currently collector is a separate service that will be merged with comedian later. Also, i updated code and made a lot of changes to DB, so please, view the updated version. 

Once we are ready with collector, will submit it here as well.
