### ISSUE TITLE
Need to investigate possible error in function rest.go/addTime

### ISSUE THREAD

**Issue by baitulakova** [maddevsio/comedian#216]
This is just a note.
mysql.go/CreateStandupTime function, that called in rest.go/addTime, sets standup time  of channel. There can be an error, because CreateStandupTime doesn't check existence of channel. And addTime sends notification "<!date^%v^Standup time at {time} added, but there is no standup users for this channel|Standup time at 12:00 added, but there is no standup users for this channel>" instead of something "The channel doesn't exist". Need to investigate necessity of checking existence of channel.

**Comment by anatoliyfedorenko** [comment]
no longer relevant
