### ISSUE TITLE
Integrate logrus to the project

### ISSUE THREAD

**Issue by gen1us2k** [maddevsio/comedian#26]
All messages should be json formatted

**Comment by malikim** [comment]
read about the library logrus

replaced fmt with s.logger

but there was a problem with this line:
`s.logger = log.New (os.Stdout, "comedian:", log.Lshortfile | log.LstdFlags)`

function logrus.New differs from the standard log.New
(you do not need to send anything to logrus)

this line also had a problem:
`slack.SetLogger (s.logger)`

it is impossible to send logrus's logs

just deleted these lines so far, to bring down and check whether new logs are working

logs worked, received following output in the terminal:

> INFO [0003] Change of presence: & {presence_change active U8EPE2HL6}
> 
> INFO. Change of presence: & {presence_change active U8EPE2HL6}
> 
> INFO Current latency: 590,207,892
> 
> INFO. Change of presence: & {presence_change active U8D7EMREC}
> 

looked at the documentation for the logger,
in the logger documentation it is possible to get the standard log from the logger
added these lines:

```
logWriter: = s.logger.Writer ()
slack.SetLogger (log.New (logWriter, "", 0))
```

but I'm not sure if this is correct, if I close the logwriter,
then the log record will fall at some point

**Comment by malikim** [comment]
integrated in rest.go & slack.go files
