### ISSUE TITLE
Issue with cyrillic named workspaces

### ISSUE THREAD

**Issue by kalashnikovisme** [maddevsio/comedian#260]
One of my workspaces is Cyrillic named. Have this little issue in the Comedian Admin panel
![Screenshot from 2020-03-28 11-58-50](https://user-images.githubusercontent.com/2001025/77818431-9fde6880-70eb-11ea-8da0-bd89ce822c36.png)

**Comment by anatoliyfedorenko** [comment]
@kalashnikovisme if you can please provide the workspace ID or real cyrillic name, I can look into it next week to see why it got messed up

**Comment by kalashnikovisme** [comment]
@anatoliyfedorenko already provided it at this issue https://github.com/maddevsio/comedian/issues/261

**Comment by anatoliyfedorenko** [comment]
@kalashnikovisme the issue was found & fixed. Two ways we can deal with the consequences. One is you just delete comedian from that workspace and install it again. Another is you tell me the exact name of the workspace and i can set it up for you.

**Comment by anatoliyfedorenko** [comment]
@kalashnikovisme please, provide the name of the team
