### ISSUE TITLE
unfortunately can't save Bot Settings

### ISSUE THREAD

**Issue by kalashnikovisme** [maddevsio/comedian#261]
In my [Cyrillic named workspace](https://github.com/maddevsio/comedian/issues/260), I can't save Bot settings.

My actions:
* launch Comedian Admin Panel
* change some Settings which I need
* doesn't find any button like `Save`, decide that it should be saved automatically
* reload page
* doesn't find my updated settings :( All settings default again

In Chrome console found this error:

```
Unchecked runtime.lastError: The message port closed before a response was received. 
     comedian_bot_settings:1 
```

**Comment by kalashnikovisme** [comment]
any updates?

**Comment by anatoliyfedorenko** [comment]
@kalashnikovisme are you an admin of the workspace? Also, if there is no "save" button, you cannot save the settings. Usually, "save" button is absent for those people who are not workspace admins

**Comment by kalashnikovisme** [comment]
@anatoliyfedorenko Slack workspace ID `TRZ42PKQD`

**Comment by anatoliyfedorenko** [comment]
@kalashnikovisme 

> are you an admin of the workspace? Also, if there is no "save" button, you cannot save the settings. Usually, "save" button is absent for those people who are not workspace admins
