### ISSUE TITLE
Standup report for manager

### ISSUE THREAD

**Issue by malikim** [maddevsio/comedian#53]
send a message to the manager at 5 pm that someone did not write the standup

**Comment by malikim** [comment]
Need to add method SelectStandupByChannelID #61

**Comment by anatoliyfedorenko** [comment]
Fixed manager notifier:
Now notifier works and checks if each team had completed their stand ups. Method selects unique channels from list of all standupers. Then checks if the channels have users who did not submit the standup. At the exact time (configured from .env) bot sends messages to manager channel with a report by channels. 
https://github.com/maddevsio/comedian/commit/da943b2c407416361eb1890b834c0b5fabe0f1e9
