### ISSUE TITLE
Conduct Full Project Research

### ISSUE THREAD

**Issue by anatoliyfedorenko** [maddevsio/comedian#80]
- [x] Understand projects' purpose and how it should work 
- [x] Get the project up and running on my local machine
- [x] Figure out the project structure
- [x] Study Slack API and how to use it
- [x] Set all the environmental variables properly
- [x] Install and run ngrok
- [x] Merge master and testing and push everything on github
- [x] Figure out what does not work at all and what does not work partially.

**Comment by anatoliyfedorenko** [comment]
Add env variables for the project through the command `sudo -H gedit /etc/environment`. Need to understand where all of them come from and how to set up them correctly!

**Comment by anatoliyfedorenko** [comment]
one more stupid problem is that the env variables get reset each time i quit terminal. That is stupid and i cannot figure out how to set them so that they will stay, not gone. :-1:

**Comment by halfb00t** [comment]
@anatoliyfedorenko 
https://github.com/maddevsio/comedian/blob/master/.env.example

**Comment by anatoliyfedorenko** [comment]
Totally forgot about the tests! Need to learn how to implement tests and how to cover whole project with tests.

**Comment by anatoliyfedorenko** [comment]
Was able to launch project localy using Docker! Now will move to study all the issues and solve them!
